#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC 
#define SPEAK_BUTTON_GPIO       GPIO_NUM_39 
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC 

#ifdef CONFIG_LCD_GC9A01_240X240
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#else
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_38 //GPIO_NUM_42 -> GPIO_NUM_38
#endif

#define DISPLAY_MOSI_PIN      GPIO_NUM_41 //GPIO_NUM_47 -> GPIO_NUM_41
#define DISPLAY_CLK_PIN       GPIO_NUM_42 //GPIO_NUM_21 -> GPIO_NUM_42
#define DISPLAY_DC_PIN        GPIO_NUM_40
#define DISPLAY_RST_PIN       GPIO_NUM_45 
#define DISPLAY_CS_PIN        GPIO_NUM_47 //GPIO_NUM_41 -> GPIO_NUM_47


#ifdef CONFIG_LCD_ST7789_240X280
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  280
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  20
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif


#ifdef CONFIG_LCD_GC9A01_240X240
#define LCD_TYPE_GC9A01_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#endif // _BOARD_CONFIG_H_
